.SUFFIXES:
ifeq ($(strip $(PSL1GHT)),)
$(error "PSL1GHT must be set in the environment.")
endif

include $(PSL1GHT)/ppu_rules

#---------------------------------------------------------------------------------
ifeq ($(strip $(PLATFORM)),)

export BASEDIR		:= $(CURDIR)

endif
#---------------------------------------------------------------------------------

INCLUDES	:= -I$(BASEDIR)/include -I$(PSL1GHT)/ppu/include
CFLAGS		+= -O2 -Wall -DBIGENDIAN -fno-strict-aliasing $(INCLUDES)

LIBCHEATS	:= src/cheatlist.o src/libcheats.o src/mystring.o src/parser.o

%.o: %.c
	@echo "[CC]  $(notdir $<)"
	@$(CC) $(DEPSOPTIONS) -DUSE_MP3 $(CFLAGS) $(INCLUDES) -c $< -o $@


#---------------------------------------------------------------------------------
libconfig.a: $(LIBCONFIG)
#---------------------------------------------------------------------------------

	@echo "[AR]  $(notdir $@)"
	@$(AR) -rcs $@ $^

#---------------------------------------------------------------------------------
install: libcheats.a
#---------------------------------------------------------------------------------

	@echo "[CP]  $(notdir $@)"
	@cp -f libcheats.a $(PORTLIBS)/lib/
	@cp -f include/libcheats.h $(PORTLIBS)/include/
	@rm -f *.d
	@rm -f $(LIBCHEATS)
	@rm -f *.a

#---------------------------------------------------------------------------------
clean:
#---------------------------------------------------------------------------------
	
	rm -f *.d
	rm -f src/*.o
	rm -f *.a
